dist: trusty

services:
  - docker

stages:
  - Build&Push

jobs:
  include:
    - stage: "Build&Push"
      script: 
        make build && \
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && \
        make push
