language: node_js
services:
  - docker
stages:
  - Build
  - name: Push
    if: branch = master

jobs:
  include:
    - stage: "Build"
      script: 
        make build
    - stage: "Push"
      script:
        make push
