language: node_js
services:
  - docker

jobs:
  include:
    - stage: "Build"
      script: 
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - cat .git/refs/heads/$BRANCH
        - docker build --build-arg BRANCH=$BRANCH -t caiocezart/docker-node-ci:$TRAVIS_BUILD_NUMBER .
        - docker run -d -e port=5000 -p 5000:5000 caiocezart/docker-node-ci:$TRAVIS_BUILD_NUMBER
        - docker ps -a