language: nodejs

services:
  - docker

stages:
  - Build
  - name: Push
    if: branch = master

jobs:
  include:
    - stage: "Build"
      script:
        - make build
    - stage: "Push"
      script: 
        - make build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make push
