language: node_js
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
services:
  - docker

jobs:
  include:
    - stage: "Build"
      script: 
        - docker build --build-arg BRANCH=$BRANCH -t caiocezart/docker-node-ci .
        - docker run -d -e port=5000 -p 5000:5000 caiocezart/docker-node-ci
        - docker ps -a
        - curl localhost:5000/healthcheck