language: node_js
services:
  - docker
stages:
  - Build
  - name: Push
    if: branch = master

jobs:
  include:
    - stage: "Build"
      script: 
        - export SHORT_SHA=$(echo $TRAVIS_COMMIT | head -c 7)
        - docker build --build-arg COMMIT_HASH=$TRAVIS_COMMIT -t caiocezart/docker-node-ci:$SHORT_SHA .
    - stage: "Push"
      script: 
        - export SHORT_SHA=$(echo $TRAVIS_COMMIT | head -c 7)
        - docker build --build-arg COMMIT_HASH=$TRAVIS_COMMIT -t caiocezart/docker-node-ci:$SHORT_SHA .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push caiocezart/docker-node-ci:$SHORT_SHA